Controllers/DanhMucController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QuanLyBanHang2.Models;

namespace QuanLyBanHang2.Controllers
{
    public class DanhMucController : Controller
    {
        DatabaseSanPhamDataContext _context = new DatabaseSanPhamDataContext("Data Source=DESKTOP-KSC3C39\\SQLEXPRESS;Initial Catalog=QuanLyBanHang;Integrated Security=True;TrustServerCertificate=True");
        // GET: DanhMuc
        public ActionResult Index()
        {   
            var x = _context.tbl_DanhMucs.ToList();
            return View(x);
        }

        [HttpPost]
        public ActionResult GetListDanhMuc()
        {
            
            List < tbl_DanhMuc > a = _context.tbl_DanhMucs.ToList();
            return Json(new
            {
                data = a,
                hoten = "Ta Van Long",
                sdt = "0386404269"
            }, JsonRequestBehavior.AllowGet) ;
            
        }

    }
}

Views/DanhMuc/Index.cshtml
@{
    ViewBag.Title = "Danh sách danh mục";
}
<div>
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Ten Danh Muc</th>
                <th>Mo ta</th>
                @*<th>Id Danh Muc Cha</th>*@
                <th>Ten Danh Muc Cha</th>
            </tr>
        </thead>
        <tbody id="categoryList">

        </tbody>
    </table>
</div>
<script type="text/javascript">
        $(document).ready(function () {
            // AJAX request to load categories
            $.ajax({
                url: '@Url.Action("GetListDanhMuc", "DanhMuc")',
                type: 'POST',
                dataType: 'json',
                success: function (response) {
                    //var str = "";
                    //$.each(data, function (Index, danhMuc) {
                    //    str += "<tr><td>" + danhMuc.Id + "</td>\
                    //                <td>"+ danhMuc.TenDanhMuc + "</td>\
                    //                <td>" + danhMuc.MoTa + "</td>\
                    //                <td>" + danhMuc.IdDanhMucCha + "</td>\
                    //            </tr>\
                    //    ";
                    //});
                    //console.log(str);
                    //document.getElementById("categoryList").innerHTML = str;
                    let danhSachDM = response.data;
                    let danhMucMap = {};
                    $.each(danhSachDM, function (Index, danhMuc) {
                        danhMucMap[danhMuc.Id] = danhMuc;
                    });


                    let tbody = $("#categoryList");
                    $.each(danhSachDM, function (Index, danhMuc) {
                        let tenDMCha = "Khong co";
                        if (danhMuc.IdDanhMucCha) {
                            let danhMucCha = danhMucMap[danhMuc.IdDanhMucCha];
                            tenDMCha = danhMucCha.TenDanhMuc;
                        }

                        tbody.append("<tr><td>" + danhMuc.Id + "</td>\
                                    <td>"+ danhMuc.TenDanhMuc + "</td>\
                                    <td>" + danhMuc.MoTa + "</td>\
                                    <td>" + tenDMCha + "</td>\
                                </tr>\
                        ");

                    });

                },
                error: function () {
                    alert('Error loading categories.');
                }
            });
        });
</script>

Views/DanhMuc/Show.cshtml
@model IEnumerable<QuanLyBanHang2.Models.tbl_DanhMuc>

@{
    ViewBag.Title = "Show";
}

<h2>Show</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TenDanhMuc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MoTa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdDanhMucCha)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TenDanhMuc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MoTa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdDanhMucCha)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>